version: '3.6'
services:
  chatopdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'chatopdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'chatopdb'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'chatopdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'chatopdb'
    ports:
      - '3307:3306'
    expose:
      - '3307'
